<?php

namespace Database\Seeders;

use App\Models\Produit;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


// ============================================================
// produits_seeder.php — 547 produits (343 existants + 204 nouveaux)
// prix_vente = prix client FCFA
// ============================================================

$produits = [
    ['nom' => 'Renfort CG 150 (Gros)', 'reference' => 'QAH0344', 'prix_achat' => 10, 'prix_vente' => 25, 'image' => null],
    ['nom' => 'Boulon 10/10 simple', 'reference' => 'BLN0020', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 10/20 simple', 'reference' => 'BLN0050', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 10/25 simple', 'reference' => 'BLN0012', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 8/10 complet', 'reference' => 'BLN0027', 'prix_achat' => 20, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 8/10 simple', 'reference' => 'BLN0044', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 8/20 simple', 'reference' => 'FTR0345', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Ecrou 10 simple', 'reference' => 'XCK0346', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Ecrou 13 simple', 'reference' => 'ECU0007', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Fusible simple', 'reference' => 'FSB0006', 'prix_achat' => 20, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Rondelle 10', 'reference' => 'RDL0008', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Rondelle 8', 'reference' => 'RDL0010', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Tuyau de carburant', 'reference' => 'TDC0091', 'prix_achat' => 20, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 10/25 complet', 'reference' => 'BLN0009', 'prix_achat' => 25, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 13/20 simple', 'reference' => 'BLN0018', 'prix_achat' => 25, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Rondelle 13 petit', 'reference' => 'RDL0013', 'prix_achat' => 25, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 10/20 complet', 'reference' => 'BLN0051', 'prix_achat' => 30, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Boulon 10/60 simple', 'reference' => 'BLN0016', 'prix_achat' => 30, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 13/35 simple', 'reference' => 'AFN0347', 'prix_achat' => 30, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 13/20 complet', 'reference' => 'BLN0002', 'prix_achat' => 35, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 8/20 complet', 'reference' => 'AFQ0348', 'prix_achat' => 35, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Détergent', 'reference' => 'DTT0326', 'prix_achat' => 37, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Ampoule clignotant', 'reference' => 'ACL0179', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Arret d\'huile 12-22 (LV TVS)', 'reference' => 'AHL0031', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'arret d\'huile 13-22', 'reference' => 'AHL0035', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arret d\'huile 14-28 (LV 150)', 'reference' => 'AHL0032', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'arret d\'huile 16-26', 'reference' => 'AHL0034', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'arret d\'huile 16-28', 'reference' => 'AHL0033', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arret d\'huile soupape GN', 'reference' => 'AHS0028', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Arret d\'huile soupape TVS', 'reference' => 'AHS0025', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Arret d\'huile soupage baja', 'reference' => 'OFP0349', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Attache chaine', 'reference' => 'ATC0005', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Bargue de chapement Baja', 'reference' => 'BCB0195', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 10/30 complet', 'reference' => 'VAU0350', 'prix_achat' => 40, 'prix_vente' => 0, 'image' => null],
    ['nom' => 'Boulon 13/25 complet', 'reference' => 'SIE0351', 'prix_achat' => 40, 'prix_vente' => 0, 'image' => null],
    ['nom' => 'Boulon 17/45 simple', 'reference' => 'YIC0352', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Cable d\'acceleration adapter 3M', 'reference' => 'CDA0199', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Câble nue', 'reference' => 'CBN0304', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Ecrou 14 chapeau', 'reference' => 'ECU0021', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Ecrou 17 simple', 'reference' => 'ECU0000', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Long ressort', 'reference' => 'LRS0122', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Rondelle 17 Gros', 'reference' => 'RDL0024', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Rondelle 17 petit', 'reference' => 'RDL0015', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Sère cable', 'reference' => 'SCB0038', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Bargue de chapement 150', 'reference' => 'BDC0194', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 13/50 simple', 'reference' => 'CWP0353', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 17/60 simple', 'reference' => 'USN0354', 'prix_achat' => 45, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Ecrou 17 de l\'axe', 'reference' => 'ECU0001', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Join Cylindre 150', 'reference' => 'JCD0324', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Join Cylindre Baja', 'reference' => 'JCB0331', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Ampoul veilleuse (Couleur)', 'reference' => 'AVC0280', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 10/50 complet', 'reference' => 'ZJO0355', 'prix_achat' => 50, 'prix_vente' => 0, 'image' => null],
    ['nom' => 'Boulon 10/60 complet', 'reference' => 'BLN0017', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulon 13/35 complet', 'reference' => 'BLN0003', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulon 8/30 complet', 'reference' => 'BLN0046', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Filtre a carburant', 'reference' => 'VQW0356', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Join Cylindre TVS', 'reference' => 'PSB0357', 'prix_achat' => 50, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Join Cylindre CD110', 'reference' => 'FHC0358', 'prix_achat' => 50, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Rondelle 19', 'reference' => 'RDL0045', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Tuyau de carburant Noir', 'reference' => 'GCH0359', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Selemblock d\'amortisseur', 'reference' => 'QJJ0360', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Selemblock de capot', 'reference' => 'FGY0361', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulon 13/30', 'reference' => 'BLN0335', 'prix_achat' => 60, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Rondelle 22', 'reference' => 'QPE0362', 'prix_achat' => 60, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 13/50 complet', 'reference' => 'SEJ0363', 'prix_achat' => 65, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'arret d\'huile 17-29', 'reference' => 'AHL0039', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Cale petit pignon BJ/TVS', 'reference' => 'CPP0023', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Cale petit pignon GN/150', 'reference' => 'CPP0022', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Ecrou 19 de l\'axe', 'reference' => 'ECU0026', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join Carton disque 150', 'reference' => 'JCD0320', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join Carton disque Baja', 'reference' => 'JCD0328', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join carter bobine TVS', 'reference' => 'ZQO0364', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join carter bobine 150', 'reference' => 'RVU0365', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join Carton disque bobine Baja', 'reference' => 'JCB0329', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join Carton disque TVS', 'reference' => 'JCD0327', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join Culasse 150', 'reference' => 'JCY0328', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join de Culars Baja', 'reference' => 'JDC0333', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Resort de Frein GN', 'reference' => 'RDF0297', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Resort Grand béquille Senké', 'reference' => 'RDF0343', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Resort Petite béquille GN', 'reference' => 'RPB0295', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Resort Petite béquille Senké', 'reference' => 'RPB0296', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Ressort grand bequille GN', 'reference' => 'RGB0103', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulon 17/60 complet', 'reference' => 'BLN0001', 'prix_achat' => 85, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Ampoule full stop', 'reference' => 'AES0180', 'prix_achat' => 90, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arret d\'huile 17-31', 'reference' => 'FAI0366', 'prix_achat' => 90, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Join Culasse TVS', 'reference' => 'GFY0367', 'prix_achat' => 90, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arret d\'huile 20-34', 'reference' => 'WIR0368', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Bouchon couvre chaine Baja', 'reference' => 'BCN0052', 'prix_achat' => 100, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Bouchon couvre chaine CGL', 'reference' => 'BCC0030', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 13/60 complet', 'reference' => 'BLN0019', 'prix_achat' => 100, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulon 13/70 complet', 'reference' => 'BLN0014', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 14/50 complet', 'reference' => 'KXL0369', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 17/40', 'reference' => 'BLN0011', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Bonlon porte bagage 13/90', 'reference' => 'GGO0370', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Ceinture de batterie', 'reference' => 'GPX0371', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Chargeur 150', 'reference' => 'CHA0162', 'prix_achat' => 100, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Join Culassse CD110', 'reference' => 'KFZ0372', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Join de Gorge Chapement noir', 'reference' => 'JDG0238', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Join de carburateur noir', 'reference' => 'NCB0373', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Scotch ABRO', 'reference' => 'CQU0374', 'prix_achat' => 100, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'tandeur chaine senke', 'reference' => 'KBJ0375', 'prix_achat' => 100, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Selemblock du moyaux CD110', 'reference' => 'SDM0337', 'prix_achat' => 100, 'prix_vente' => 175, 'image' => null],
    ['nom' => 'Selemblock du moyaux Senke', 'reference' => 'SDM0338', 'prix_achat' => 100, 'prix_vente' => 175, 'image' => null],
    ['nom' => 'Selemblock du moyaux Baja', 'reference' => 'SDM0339', 'prix_achat' => 100, 'prix_vente' => 175, 'image' => null],
    ['nom' => 'Selemblock du moyaux GN', 'reference' => 'SDM0340', 'prix_achat' => 100, 'prix_vente' => 175, 'image' => null],
    ['nom' => 'Selemblock demi-chassi', 'reference' => 'ZNZ0376', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'selemblock du guidon', 'reference' => 'WAS0377', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Ampoule ronde', 'reference' => 'ARN0157', 'prix_achat' => 120, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 17/100 Complet', 'reference' => 'BLN0334', 'prix_achat' => 125, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Sandoux', 'reference' => 'SDX0113', 'prix_achat' => 125, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Tandeur chaine Baja (Pour la roue)', 'reference' => 'RNG0378', 'prix_achat' => 125, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Bouchon de vidange du haut 150', 'reference' => 'QCL0379', 'prix_achat' => 150, 'prix_vente' => 300, 'image' => null],
    ['nom' => 'Boulon 17/100 simple', 'reference' => 'LYW0380', 'prix_achat' => 150, 'prix_vente' => 300, 'image' => null],
    ['nom' => 'Cale resor CGL', 'reference' => 'CRC0322', 'prix_achat' => 150, 'prix_vente' => 300, 'image' => null],
    ['nom' => 'Mano-feu stop', 'reference' => 'GNE0381', 'prix_achat' => 150, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Tuyau de respiration CG 150', 'reference' => 'XWH0382', 'prix_achat' => 150, 'prix_vente' => 250, 'image' => null],
    ['nom' => 'Bougie D8TC', 'reference' => 'BDT0308', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6200', 'reference' => 'RLT0151', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6201', 'reference' => 'RLT0145', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6202', 'reference' => 'RLT0152', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6300', 'reference' => 'RLT0149', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Ampoule H4', 'reference' => 'QPD0383', 'prix_achat' => 200, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Arret d\'huile 35-50  volant moteur CG 150', 'reference' => 'TOU0384', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arret d\'huile 32-43', 'reference' => 'NAI0385', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arret d\'huile 32-44 (Fourche P6)', 'reference' => 'AYW0386', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arret d\'huile 31-43 (fourche senke)', 'reference' => 'VHB0387', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arret d\'huile fourche TVS/Baja 30-42', 'reference' => 'WYC0388', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arrêt d\'huil 27-37', 'reference' => 'AHL0271', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arret d\'huile 30-42', 'reference' => 'MBT0389', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arrêt d\'huil 30-43', 'reference' => 'AHL0270', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arrêt d\'huil Soupap Complet Baja', 'reference' => 'ASC0247', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Douille 150', 'reference' => 'DIL0264', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Roulement 6001', 'reference' => 'RLT0148', 'prix_achat' => 200, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6302', 'reference' => 'RLT0313', 'prix_achat' => 200, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Tete de bougie', 'reference' => 'TDM0390', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Bougie A7TC YOG', 'reference' => 'BAS0309', 'prix_achat' => 220, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Roulement 6004', 'reference' => 'RLT0150', 'prix_achat' => 220, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Bavette SM', 'reference' => 'OGW0391', 'prix_achat' => 225, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Boulon porte pignon P6', 'reference' => 'LFO0392', 'prix_achat' => 225, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Petit Pignon Baja', 'reference' => 'SFI0393', 'prix_achat' => 225, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Petit Pignon TVS', 'reference' => 'ZQL0394', 'prix_achat' => 225, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Ampoule Lazer(bleu)', 'reference' => 'ALZ0200', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Bouchon vidange 150', 'reference' => 'BCV0074', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Boulon porte pignon Senke JH', 'reference' => 'NDF0395', 'prix_achat' => 250, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Boulon porte pignon Senké', 'reference' => 'BPP0317', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Boulon porte Pignon TVS', 'reference' => 'BPP0341', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'colle melange TCM', 'reference' => 'IPF0396', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'cable d\'accelerateur senke', 'reference' => 'FBQ0397', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette d\'embrayage CGL', 'reference' => 'FXW0398', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Moteur Clignotant 150', 'reference' => 'MCL0248', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Porte retriviseur cote frein CGL', 'reference' => 'BGR0399', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Roulement d\'ambreyage Baja Bj', 'reference' => 'RDB0181', 'prix_achat' => 250, 'prix_vente' => 550, 'image' => null],
    ['nom' => 'Tandeur Chaine GN', 'reference' => 'FDY0400', 'prix_achat' => 250, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Tige de frein Baja', 'reference' => 'TDF0283', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Tige de frein Senké/GN', 'reference' => 'TDF0284', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manatte de frein Senke', 'reference' => 'MDF0077', 'prix_achat' => 275, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Manette d\'embreyage Baja', 'reference' => 'MDB0078', 'prix_achat' => 275, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette d\'embreyage GN', 'reference' => 'MDG0079', 'prix_achat' => 275, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Petit Pignon 150', 'reference' => 'PPG0319', 'prix_achat' => 275, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Plaquette frein GN', 'reference' => 'PFG0156', 'prix_achat' => 275, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Boulon porte pignon Baja', 'reference' => 'OMU0401', 'prix_achat' => 300, 'prix_vente' => 450, 'image' => null],
    ['nom' => 'Boulon vidange TVS', 'reference' => 'BLN0029', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 10 plate', 'reference' => 'CAP0256', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 12 à pipe', 'reference' => 'CAP0255', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 12 plate', 'reference' => 'UEC0402', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 7 plate', 'reference' => 'CAT0251', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Disque conte', 'reference' => 'LLM0403', 'prix_achat' => 300, 'prix_vente' => 375, 'image' => null],
    ['nom' => 'Main mou', 'reference' => 'SRZ0404', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manivelle simple Senké', 'reference' => 'CKI0405', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette de frein CGL', 'reference' => 'WGE0406', 'prix_achat' => 300, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Roulement 6204', 'reference' => 'RLT0146', 'prix_achat' => 325, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Cable d\'accéleration Baja', 'reference' => 'CDB0100', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Clé 11 a pipe', 'reference' => 'LKH0407', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 10 à pipe', 'reference' => 'CAP0253', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 13 à pipe', 'reference' => 'CAP0275', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 7 à pipe', 'reference' => 'CAP0259', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Câble d\'acc Baja', 'reference' => 'CDB0302', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Câble d\'acc TVS', 'reference' => 'CDT0286', 'prix_achat' => 350, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Câble d\'accélérateur GN', 'reference' => 'CDL0290', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Manette d\'embrayage TVS', 'reference' => 'GYL0408', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette de frein Baja', 'reference' => 'WOB0409', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette de frein TVS', 'reference' => 'ZVZ0410', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette de frein simple P6', 'reference' => 'YWE0411', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Porte Rétroviseur GN CG', 'reference' => 'PRG0239', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Renfert Baja', 'reference' => 'RFB0323', 'prix_achat' => 350, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Verre de far GN', 'reference' => 'MFK0412', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Axe avant TVS YOG', 'reference' => 'BJZ0413', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe avant Baja', 'reference' => 'AAB0070', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Axe avant CGL "SENKE"', 'reference' => 'AAC0072', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Axe grand bequille CGL', 'reference' => 'AGB0065', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe grand bequille GN', 'reference' => 'AGB0066', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Boulon 27 BAJA', 'reference' => 'GUL0414', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Cable d\'ambreyage TVS', 'reference' => 'CDT0169', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Cable de frein Baja', 'reference' => 'CDF0170', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'clignotants Baja/TVS', 'reference' => 'KYZ0415', 'prix_achat' => 400, 'prix_vente' => 600, 'image' => null],
    ['nom' => 'clignotants GN125', 'reference' => 'OSE0416', 'prix_achat' => 400, 'prix_vente' => 600, 'image' => null],
    ['nom' => 'Câble d\'embrayage TVC', 'reference' => 'CDT0287', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Câble d\'ampreyage GN', 'reference' => 'CDY0288', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Câble d\'embrayage Baja', 'reference' => 'CDB0292', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Câble d\'embrayage Baja 3M', 'reference' => 'CDB0303', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Câble de Frein Senké', 'reference' => 'CDF0291', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Câble de Frein TVS', 'reference' => 'CDF0285', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Gorge de filtre a air', 'reference' => 'HZP0417', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Paire tige Soupape 150/200', 'reference' => 'TSP0282', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'ressort de demarreur baja', 'reference' => 'OTB0418', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Roulement 6304', 'reference' => 'RLT0147', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Ver de far Senké', 'reference' => 'VDF0172', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Axe arriere CGL "SENKE"', 'reference' => 'AAC0067', 'prix_achat' => 450, 'prix_vente' => 750, 'image' => null],
    ['nom' => 'Axe arriere GN "P6"', 'reference' => 'AAG0068', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe du pouse', 'reference' => 'ADP0315', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Bille de guidon  senke', 'reference' => 'PNW0419', 'prix_achat' => 450, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Chaine moteur 25H-88L', 'reference' => 'CHM0168', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Clé 14 plate', 'reference' => 'CAP0257', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Clé 16 plate', 'reference' => 'CAP0258', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Pochette de join complet CG125', 'reference' => 'PGC0207', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pochette join Baja', 'reference' => 'PJB0303', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pochette join CG150', 'reference' => 'PDC0302', 'prix_achat' => 450, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Pochette join complet TVS', 'reference' => 'PJC0206', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Roulement 6205', 'reference' => 'EYC0420', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Soupape  TVS', 'reference' => 'SPT0175', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Soupape Baja SM', 'reference' => 'SBS0109', 'prix_achat' => 450, 'prix_vente' => 850, 'image' => null],
    ['nom' => 'Soupape CD10', 'reference' => 'SCD0110', 'prix_achat' => 450, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Soupape CG150', 'reference' => 'SPC0176', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Soupape TVS SM', 'reference' => 'STS0114', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Tandeur chaîne Moteur Baja', 'reference' => 'TCM0319', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Tandeur Chaîne Moteur TVS', 'reference' => 'TCM0320', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Arrête d\'huil Soupape gomet', 'reference' => 'ASG0249', 'prix_achat' => 500, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Axe arriere Hight Jack', 'reference' => 'AAH0073', 'prix_achat' => 500, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Axe arriere TVS', 'reference' => 'AAT0069', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe demi-chassi Baja', 'reference' => 'ADC0071', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cole moteur', 'reference' => 'CMT0196', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Câble d\'ambrayage 200', 'reference' => 'CDT0289', 'prix_achat' => 500, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Câble de Conteur GN', 'reference' => 'CDC0293', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Câble de Moteur GN', 'reference' => 'CDM0294', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Garniture CG125 3Z$W8', 'reference' => 'GNC0053', 'prix_achat' => 500, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Garniture TVS 3Z$W8', 'reference' => 'GNT0055', 'prix_achat' => 500, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Garniture TVS 3Z8W6', 'reference' => 'GNT0048', 'prix_achat' => 500, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Gorge de carburateur ALU', 'reference' => 'EPR0421', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Manivelle d\'embrayage CG 150', 'reference' => 'GDX0422', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Petit clakson', 'reference' => 'PTC0160', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pochette de join CD 110', 'reference' => 'GPQ0423', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Resort de démarreur Baja', 'reference' => 'RDD0321', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Resort de démarreur TVS', 'reference' => 'RDD0322', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Robinet Senke', 'reference' => 'KPN0424', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Roulement 6005', 'reference' => 'RLT0314', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Garniture Baja 3Z', 'reference' => 'YFS0425', 'prix_achat' => 550, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Garniture CG125 3Z$W8', 'reference' => 'GKR0426', 'prix_achat' => 550, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Garniture GN 38Z8W6', 'reference' => 'GNT0047', 'prix_achat' => 550, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Segment TVS STD+', 'reference' => 'HIT0427', 'prix_achat' => 550, 'prix_vente' => 950, 'image' => null],
    ['nom' => 'Bille de guidon GN', 'reference' => 'BLZ0428', 'prix_achat' => 600, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Bille de guidon senke JH', 'reference' => 'ZBF0429', 'prix_achat' => 600, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Boulon 27 TVS  YOG', 'reference' => 'GYW0430', 'prix_achat' => 600, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Levier vitesse TVS', 'reference' => 'LVT0059', 'prix_achat' => 600, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Petite Pince', 'reference' => 'PPC0236', 'prix_achat' => 600, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Pompe a l\'huile', 'reference' => 'WJE0431', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'relai de demarreur', 'reference' => 'VSP0432', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Robinet GN', 'reference' => 'ZRA0433', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Segment 150 SM STD +', 'reference' => 'SGS0115', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Segment Baja', 'reference' => 'SGB0105', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Garniture Baja 3M', 'reference' => 'VHR0434', 'prix_achat' => 680, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Bille de guidon Baja', 'reference' => 'BDG0159', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Bille de guidon TVS', 'reference' => 'BDG0158', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'CDI 150', 'reference' => 'CDI0208', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Charbong', 'reference' => 'CHB0324', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé à bougie (Petit)', 'reference' => 'CAB0273', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé a douille 14', 'reference' => 'YDD0435', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Disque simple 150', 'reference' => 'DSP0307', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Disque simple TVS WDFR', 'reference' => 'DST0306', 'prix_achat' => 700, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Garniture TVS 3M$W6', 'reference' => 'GNT0054', 'prix_achat' => 700, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Gros clokson', 'reference' => 'GSC0161', 'prix_achat' => 700, 'prix_vente' => 1100, 'image' => null],
    ['nom' => 'guide chaine baja', 'reference' => 'COH0436', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Guide Chaîne TVS', 'reference' => 'GCT0250', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Guide soupape 150', 'reference' => 'GSP0166', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Guide soupape TVS TP oem', 'reference' => 'GST0167', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'large Bavette', 'reference' => 'PSF0437', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Moteur counter GN', 'reference' => 'MCG0312', 'prix_achat' => 700, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Roulement 6008', 'reference' => 'QGM0438', 'prix_achat' => 700, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Arrêt d\'huil Soupape TVS Origine', 'reference' => 'AHL0272', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé 17 à pipe', 'reference' => 'CAP0252', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé 18 à pipe', 'reference' => 'CAP0254', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Longue 10', 'reference' => 'LNG0260', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Longue clé à bougie', 'reference' => 'LCB0316', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Pot de Graisse (Petite boite)', 'reference' => 'XVC0439', 'prix_achat' => 750, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Robinet GN avec filtre', 'reference' => 'LHA0440', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Tandeur TVS (de roue)', 'reference' => 'TDT0262', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Ampoule (Strong Light) TVS', 'reference' => 'UQG0441', 'prix_achat' => 800, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Clé 19 plate', 'reference' => 'TOL0442', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé à douille 10', 'reference' => 'CAD0267', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé à douille 13', 'reference' => 'CAD0268', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'clé a douille 12', 'reference' => 'ABW0443', 'prix_achat' => 800, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Garniture RX125 SM', 'reference' => 'XOV0444', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Garniture TVS SM', 'reference' => 'GNT0049', 'prix_achat' => 800, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Segment CG200 STD +', 'reference' => 'SCG0154', 'prix_achat' => 800, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Soupage TVS YOG', 'reference' => 'PDD0445', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Soupape Baja YOG', 'reference' => 'SBY0108', 'prix_achat' => 800, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Soupage CG 200 longue tete', 'reference' => 'IXU0446', 'prix_achat' => 800, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Soupage 200 courte tete', 'reference' => 'WXF0447', 'prix_achat' => 800, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Tournevis plat', 'reference' => 'GCU0448', 'prix_achat' => 800, 'prix_vente' => 0, 'image' => null],
    ['nom' => 'Huile de frein GM', 'reference' => 'HDF0088', 'prix_achat' => 850, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Demareur a pied CGL "SENKE"', 'reference' => 'DPC0061', 'prix_achat' => 900, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Disque simple Baja SM', 'reference' => 'WKQ0449', 'prix_achat' => 900, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Disque simple Baja YOG', 'reference' => 'DSB0305', 'prix_achat' => 900, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Marqeur de Vitesse GN', 'reference' => 'MDV0246', 'prix_achat' => 900, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Axe Petit Pignon CG 150', 'reference' => 'EYW0450', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Axe levier de vitesse CG 150', 'reference' => 'ZVW0451', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Balance 150 CG 750 3M', 'reference' => 'BCG0243', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Balance 150 CG 750 Ordinaire', 'reference' => 'BCG0244', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Bouchon réservoir Baja', 'reference' => 'ATI0452', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Cable de frein avant GN', 'reference' => 'YUW0453', 'prix_achat' => 1000, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Chambre a air 300-18 SM', 'reference' => 'CHA0184', 'prix_achat' => 1000, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'cle a douille 22', 'reference' => 'VGU0454', 'prix_achat' => 1000, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Demareur a pied CG "SANILI"', 'reference' => 'DPC0060', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Grosse Pince', 'reference' => 'GPC0237', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Lazer SM 12V-GT(noir)', 'reference' => 'LSM0080', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Levier de vitesse CG 150', 'reference' => 'CWW0455', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Paire de capeau Senké', 'reference' => 'CAS0171', 'prix_achat' => 1000, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Pince à coupé', 'reference' => 'PAC0235', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Pédale de frein CD110', 'reference' => 'PDF0203', 'prix_achat' => 1000, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Retroviseur CGL125 Mr Li', 'reference' => 'RTS0057', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Retroviseur GN125 SM', 'reference' => 'RTS0058', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Axe petit pignon GN', 'reference' => 'APP0281', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Bouchon réservoir Senké', 'reference' => 'BAS0274', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'CDI 200', 'reference' => 'CDI0209', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Clé contact CGL J$H', 'reference' => 'CCJ0093', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Clé contact CGL SM', 'reference' => 'CCC0092', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Clé à douille 24', 'reference' => 'CAD0265', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Couvre siège Baja', 'reference' => 'CSB0314', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Couvre siège GN (P6)', 'reference' => 'CSG0313', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Couvre siège Senké', 'reference' => 'CSS0312', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Instinteur 500 mL Abro', 'reference' => 'IAG0089', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Poignier d\'allumage GN coter droit', 'reference' => 'PDG0320', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Poignier d\'allumage CGL Gauche', 'reference' => 'PDC0120', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Poignier d\'allumage CGL cote droit', 'reference' => 'FVL0456', 'prix_achat' => 1100, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Pédale de frein Senké', 'reference' => 'PDF0204', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Pédale de frein TVS', 'reference' => 'PDF0202', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Pedale de fein baja', 'reference' => 'HUF0457', 'prix_achat' => 1100, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Spray ABRO Jaune', 'reference' => 'SAJ0086', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Spray ABRO Rouge', 'reference' => 'SAR0085', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Spray Pro Loc Blanc', 'reference' => 'SPB0087', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'bobine haute tension 150', 'reference' => 'AFI0458', 'prix_achat' => 1200, 'prix_vente' => 1700, 'image' => null],
    ['nom' => 'Bobine Baja YOG', 'reference' => 'BBY0186', 'prix_achat' => 1200, 'prix_vente' => 1700, 'image' => null],
    ['nom' => 'chaine moteur complet CD110', 'reference' => 'WZH0459', 'prix_achat' => 1200, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Chambre à air 275-17 SM', 'reference' => 'CHA0342', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Chambre à air 275-18 GST', 'reference' => 'CAA0309', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Chambre à air 275-18 SM', 'reference' => 'CAA0299', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Chambre à air 350-16 SM', 'reference' => 'CAA0310', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Clé 21 plate', 'reference' => 'QKZ0460', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arrière Baja', 'reference' => 'PAB0134', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arriere GN ordinaire', 'reference' => 'NYC0461', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arriere Senke', 'reference' => 'ZEZ0462', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arrière GN 3M', 'reference' => 'PAG0125', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arrière TVS', 'reference' => 'PAT0128', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arrière WY-CG 4T', 'reference' => 'PAW0135', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon marche arriere 200 12T', 'reference' => 'PMA0165', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon marche arriere 200 13T', 'reference' => 'PMA0163', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon marhe arriere 200 11T', 'reference' => 'PMA0164', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Spray KEM gris', 'reference' => 'GCL0463', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Spray ABRO gris', 'reference' => 'SIP0464', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignon arrière CB-125', 'reference' => 'PAC0123', 'prix_achat' => 1250, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Couvre petit pignon GN', 'reference' => 'NKO0465', 'prix_achat' => 1300, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Couvre chaine GN', 'reference' => 'GSA0466', 'prix_achat' => 1300, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Huile Darsoney SAE 50', 'reference' => 'HDS0081', 'prix_achat' => 1300, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Lazer WDFR tête verte', 'reference' => 'LTV0075', 'prix_achat' => 1300, 'prix_vente' => 1600, 'image' => null],
    ['nom' => 'Levier de vitesse Baja', 'reference' => 'YNS0467', 'prix_achat' => 1300, 'prix_vente' => 1700, 'image' => null],
    ['nom' => 'Pignon troisieme CG 150', 'reference' => 'TRJ0468', 'prix_achat' => 1300, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston Baja Baja STD +', 'reference' => 'PBB0187', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston Baja STD + SM', 'reference' => 'PBS0189', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston Baja STD+ WDFR', 'reference' => 'BRI0469', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston Baja STD ++', 'reference' => 'PBS0190', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston CD110 STD +', 'reference' => 'PCD0188', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston CD110 STD + SM', 'reference' => 'PCD0116', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston CG150 STD +', 'reference' => 'PCG0193', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston CG 125 STD+ (petite sanili) Ordinaire', 'reference' => 'IWS0470', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston CG150 STD ++', 'reference' => 'PCG0192', 'prix_achat' => 1400, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston TVS STD + SM', 'reference' => 'PTS0117', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston TVS STD ++ JYC', 'reference' => 'PTS0118', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Frein a main P6 SM', 'reference' => 'HIK0471', 'prix_achat' => 1450, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Frein a main P6 JYC', 'reference' => 'KHD0472', 'prix_achat' => 1450, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Piston baja STD++ DC', 'reference' => 'KYR0473', 'prix_achat' => 1450, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Piston TVS  STD+ SILVO', 'reference' => 'XQH0474', 'prix_achat' => 1450, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Chateau d\'huile', 'reference' => 'OAH0475', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Clé contact Baja SM', 'reference' => 'CCB0098', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Clé contact TVS SM', 'reference' => 'CCT0094', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Demareur a pied Baja', 'reference' => 'DPB0062', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Demareur a pied TVS', 'reference' => 'DPT0063', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Frein a main P6 JHSY', 'reference' => 'LPR0476', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Garnitur d\'origine Simba', 'reference' => 'GD00318', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Garniture 200 Petit-Model', 'reference' => 'GPM0144', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Garniture d\'origine Baja', 'reference' => 'GDB0332', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Huile de direction ATF', 'reference' => 'HDD0084', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Huile Mixalub 20W-50', 'reference' => 'HML0111', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Lazer SM tête verte', 'reference' => 'LTV0076', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston BAJA STD++ YOG', 'reference' => 'MLF0477', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston CG 125 STD+ (petite sanili) 3M', 'reference' => 'MXU0478', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Piston TVS STD+ YOG', 'reference' => 'ECN0479', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Piston TVS STD++ YOG', 'reference' => 'QIV0480', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Power Oil SAE 50', 'reference' => 'TRF0481', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Poignier d\'alllumage complet Baja Cote Gauche', 'reference' => 'FAG0482', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'poignier d\'allumage complet GN coté Gauche', 'reference' => 'PDC0121', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Porte disque 150 4T', 'reference' => 'PDQ0180', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Porte disque Baja', 'reference' => 'MWB0483', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Clé contact Baja hongcheng', 'reference' => 'CCB0096', 'prix_achat' => 1600, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Clé contact BAJA SILVO', 'reference' => 'KQF0484', 'prix_achat' => 1600, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Huile Boss SAE 50', 'reference' => 'SMG0485', 'prix_achat' => 1600, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Huile Darsoney SAE 90', 'reference' => 'RAT0486', 'prix_achat' => 1600, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Piston CG 150 STD+ SM en boite', 'reference' => 'UCL0487', 'prix_achat' => 1600, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston TVS STD + 3M$W6', 'reference' => 'PTS0119', 'prix_achat' => 1600, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Piston TVS STD+ SM en boite', 'reference' => 'EYN0488', 'prix_achat' => 1600, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'lazer 3 fils LED', 'reference' => 'BGW0489', 'prix_achat' => 1650, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Axe de démarreur 150', 'reference' => 'ADD0241', 'prix_achat' => 1700, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Chaine simple', 'reference' => 'LUR0490', 'prix_achat' => 1700, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Chambre a air 250-17 CST', 'reference' => 'CAA182', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Chambre a air 275-18 CST', 'reference' => 'CHA0183', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Chambre a air 350-16 CST', 'reference' => 'CHA0201', 'prix_achat' => 1700, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Clé contact Baja 3M$W6', 'reference' => 'CCB0097', 'prix_achat' => 1700, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Clé à douille 30', 'reference' => 'CAD0266', 'prix_achat' => 1700, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Demareur a pied 200 1T', 'reference' => 'DPN0064', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Garniture 200 Grand-Model', 'reference' => 'GGM0143', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Guidon Baja', 'reference' => 'ZPY0491', 'prix_achat' => 1700, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Guidon GN (P6)', 'reference' => 'GDN0311', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Porte disque 150 6T 3M', 'reference' => 'PDS0178', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Porte disque CG125 5T', 'reference' => 'PDC0173', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Retroviseur Baja SM', 'reference' => 'RTS0056', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'clé contact complet TVS', 'reference' => 'XPS0492', 'prix_achat' => 1800, 'prix_vente' => 2300, 'image' => null],
    ['nom' => 'Piston Jet 150 STD +', 'reference' => 'PSJ0185', 'prix_achat' => 1800, 'prix_vente' => 2100, 'image' => null],
    ['nom' => 'Piston TVS 160 STD +', 'reference' => 'PTV0191', 'prix_achat' => 1800, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Porte Pignon 3M TVS', 'reference' => 'NVO0493', 'prix_achat' => 1800, 'prix_vente' => 2300, 'image' => null],
    ['nom' => 'Retroviseur Baja YOG', 'reference' => 'XTM0494', 'prix_achat' => 1800, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Chanbre a air 500-12 SM', 'reference' => 'GGQ0495', 'prix_achat' => 2000, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Feu Stop arriere Baja', 'reference' => 'TNQ0496', 'prix_achat' => 2000, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Porte disque TVS TVS', 'reference' => 'PDT0174', 'prix_achat' => 2000, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Capot GN', 'reference' => 'HCH0497', 'prix_achat' => 2200, 'prix_vente' => 2700, 'image' => null],
    ['nom' => 'Chargeur 200 petit modele', 'reference' => 'HIO0498', 'prix_achat' => 2200, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Croisons', 'reference' => 'DGS0499', 'prix_achat' => 2200, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Pôt Feux Stop Baja', 'reference' => 'PFS0232', 'prix_achat' => 2200, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Huile Bocom SAE 40', 'reference' => 'SBK0500', 'prix_achat' => 2250, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Bouchon réservoir TVS', 'reference' => 'OKF0501', 'prix_achat' => 2300, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Porte pignon GN', 'reference' => 'PPG0304', 'prix_achat' => 2300, 'prix_vente' => 2700, 'image' => null],
    ['nom' => 'Pose pied avant Baja', 'reference' => 'PPA0205', 'prix_achat' => 2300, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Boitier 150', 'reference' => 'BTI0310', 'prix_achat' => 2500, 'prix_vente' => 2900, 'image' => null],
    ['nom' => 'Couvre chaine hight Jack', 'reference' => 'CCH0198', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Feu Stop arriere P6', 'reference' => 'KXP0502', 'prix_achat' => 2500, 'prix_vente' => 2900, 'image' => null],
    ['nom' => 'Feu stop TVS', 'reference' => 'SWT0503', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Huile AyanÖl 4T', 'reference' => 'HAQ0082', 'prix_achat' => 2500, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Huile Standard', 'reference' => 'HLS0043', 'prix_achat' => 2500, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Portance du haut CGL', 'reference' => 'PDH0276', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Portance du haut GN', 'reference' => 'PDH0231', 'prix_achat' => 2500, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Porte pignon CGL', 'reference' => 'PPC0321', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Porté garniture TVS', 'reference' => 'PGT0234', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Pâte full stop TVS', 'reference' => 'PFS0197', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Balance Baja', 'reference' => 'BBI0242', 'prix_achat' => 2600, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Pheseau CGL', 'reference' => 'PHC0316', 'prix_achat' => 2600, 'prix_vente' => 2900, 'image' => null],
    ['nom' => 'Pheseau GN', 'reference' => 'PHG0318', 'prix_achat' => 2600, 'prix_vente' => 2900, 'image' => null],
    ['nom' => 'Abre a Came complet JYC CG 150', 'reference' => 'JAJ0504', 'prix_achat' => 2700, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Axe de levier de vitesse TVS YOG', 'reference' => 'TWY0505', 'prix_achat' => 2700, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Garde boue Avant Senké', 'reference' => 'GBA0300', 'prix_achat' => 2700, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Pheseau Baja', 'reference' => 'PHB0319', 'prix_achat' => 2700, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Pheseau TVS', 'reference' => 'PHT0317', 'prix_achat' => 2700, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Huile ELF', 'reference' => 'HLE0042', 'prix_achat' => 2750, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Bobine 200', 'reference' => 'KTO0506', 'prix_achat' => 2800, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Disque complet TVS SM', 'reference' => 'DCT0301', 'prix_achat' => 2800, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Disque complet TVS SM', 'reference' => 'PFF0507', 'prix_achat' => 2800, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Disque Complet 150 5T 6D', 'reference' => 'LAI0508', 'prix_achat' => 2800, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Poignier d\'allumage COMPLET TVS', 'reference' => 'RKE0509', 'prix_achat' => 2800, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Pot de far Baja', 'reference' => 'PFB0131', 'prix_achat' => 2800, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Arbre à Camp Baja Baja', 'reference' => 'AAC0263', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Axe petit pignon Baja Ordinaire', 'reference' => 'MDQ0510', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Axe de Petit Pignon Baja original', 'reference' => 'APP0261', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Boitier 200', 'reference' => 'AKO0511', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Chargeur 200 gros modele', 'reference' => 'AQD0512', 'prix_achat' => 3000, 'prix_vente' => 3700, 'image' => null],
    ['nom' => 'Contact Complet GN', 'reference' => 'CLG0269', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Couvre chaine TVS', 'reference' => 'MBJ0513', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Disque complet Baja SM', 'reference' => 'FIT0514', 'prix_achat' => 3000, 'prix_vente' => 3700, 'image' => null],
    ['nom' => 'Garde boue Avant P6', 'reference' => 'JTV0515', 'prix_achat' => 3000, 'prix_vente' => 3800, 'image' => null],
    ['nom' => 'Garde boue arriere senke', 'reference' => 'GCA0516', 'prix_achat' => 3000, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Lazer Oeil de nuit', 'reference' => 'OZJ0517', 'prix_achat' => 3000, 'prix_vente' => 3400, 'image' => null],
    ['nom' => 'Pare-choc P6', 'reference' => 'QUQ0518', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Porte garniture Baja YOG', 'reference' => 'TYF0519', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Poigner d\'allumage complet Baja', 'reference' => 'ADD0520', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Porte garniture GN', 'reference' => 'PGG0315', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Pot de far GN 125', 'reference' => 'ROF0521', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Yamalube 4T', 'reference' => 'YLB0040', 'prix_achat' => 3029, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Huile National jaune 20W-50', 'reference' => 'HNJ0112', 'prix_achat' => 3100, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Pot de far TVS', 'reference' => 'PFT0133', 'prix_achat' => 3100, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Transmission CD110 3M$W6', 'reference' => 'TCD0126', 'prix_achat' => 3100, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Transmission TVS 3M', 'reference' => 'STE0522', 'prix_achat' => 3100, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Garde boue avant Baja', 'reference' => 'PTC0523', 'prix_achat' => 3200, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Huile TVS', 'reference' => 'HLT0041', 'prix_achat' => 3200, 'prix_vente' => 3400, 'image' => null],
    ['nom' => 'Pot de far CG125 (Long Chassi)', 'reference' => 'PDF0132', 'prix_achat' => 3200, 'prix_vente' => 3800, 'image' => null],
    ['nom' => 'Transmission CGL 3M$W6', 'reference' => 'TCG0127', 'prix_achat' => 3250, 'prix_vente' => 3800, 'image' => null],
    ['nom' => 'Compteur Baja', 'reference' => 'VZC0524', 'prix_achat' => 3300, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Compteur GN', 'reference' => 'AIR0525', 'prix_achat' => 3300, 'prix_vente' => 3700, 'image' => null],
    ['nom' => 'Disque complet Baja YOG', 'reference' => 'DCB0300', 'prix_achat' => 3350, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Transmission Baja 3M$W6', 'reference' => 'TBM0130', 'prix_achat' => 3350, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Carburateur 150 SM', 'reference' => 'CBT0095', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Carburateur TVS TVS', 'reference' => 'CCT0099', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Portance du bas Complet GN', 'reference' => 'PDB0277', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Portance TVS', 'reference' => 'DTS0278', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Pot de far CG d\'origine', 'reference' => 'YKS0526', 'prix_achat' => 3500, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Carburateur TVS SM', 'reference' => 'BRQ0527', 'prix_achat' => 3700, 'prix_vente' => 4300, 'image' => null],
    ['nom' => 'Porte Pignon Baja', 'reference' => 'CUW0528', 'prix_achat' => 3700, 'prix_vente' => 4200, 'image' => null],
    ['nom' => 'Axe petit pignon Baja YOG', 'reference' => 'PDZ0529', 'prix_achat' => 3800, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Demarreur automatique CG 150', 'reference' => 'UJL0530', 'prix_achat' => 4000, 'prix_vente' => 4500, 'image' => null],
    ['nom' => 'Transmission CB-125', 'reference' => 'TCD0124', 'prix_achat' => 4000, 'prix_vente' => 4500, 'image' => null],
    ['nom' => 'Huile Yamalub Pirogue 2', 'reference' => 'HYP0083', 'prix_achat' => 4050, 'prix_vente' => 4500, 'image' => null],
    ['nom' => 'Petit Lekteur', 'reference' => 'PLK0155', 'prix_achat' => 4700, 'prix_vente' => 5300, 'image' => null],
    ['nom' => 'Pneu 275-17 local', 'reference' => 'PNL0138', 'prix_achat' => 4700, 'prix_vente' => 5500, 'image' => null],
    ['nom' => 'Pneu 275-18 local', 'reference' => 'PNL0139', 'prix_achat' => 4700, 'prix_vente' => 5500, 'image' => null],
    ['nom' => 'Demareur automatique CG200', 'reference' => 'DLT0153', 'prix_achat' => 5000, 'prix_vente' => 5500, 'image' => null],
    ['nom' => 'batterie senke 12N6', 'reference' => 'JNI0531', 'prix_achat' => 5100, 'prix_vente' => 5600, 'image' => null],
    ['nom' => 'Batterie TVS', 'reference' => 'WVC0532', 'prix_achat' => 5300, 'prix_vente' => 5800, 'image' => null],
    ['nom' => 'Pneu 300-17 local', 'reference' => 'PNL0142', 'prix_achat' => 5500, 'prix_vente' => 6000, 'image' => null],
    ['nom' => 'Pneu 300-18 local', 'reference' => 'PNL0141', 'prix_achat' => 5500, 'prix_vente' => 6000, 'image' => null],
    ['nom' => 'Battérie 12 Nb (Senke)', 'reference' => 'BTS0090', 'prix_achat' => 5600, 'prix_vente' => 6000, 'image' => null],
    ['nom' => 'Batterie 12 N9', 'reference' => 'YQV0533', 'prix_achat' => 6500, 'prix_vente' => 7000, 'image' => null],
    ['nom' => 'Compteur senke original', 'reference' => 'SLT0534', 'prix_achat' => 6500, 'prix_vente' => 7500, 'image' => null],
    ['nom' => 'Amortisseur Baja ISUUO', 'reference' => 'ABI0179', 'prix_achat' => 7000, 'prix_vente' => 7500, 'image' => null],
    ['nom' => 'Cylindre TVS', 'reference' => 'ZHV0535', 'prix_achat' => 7200, 'prix_vente' => 7700, 'image' => null],
    ['nom' => 'Amortisseur Baja JYC', 'reference' => 'ABJ0177', 'prix_achat' => 7500, 'prix_vente' => 8200, 'image' => null],
    ['nom' => 'Amortisseur Baja SOMON', 'reference' => 'ABS0178', 'prix_achat' => 7500, 'prix_vente' => 8000, 'image' => null],
    ['nom' => 'Cylindre 150 SM', 'reference' => 'CSM0245', 'prix_achat' => 7500, 'prix_vente' => 8200, 'image' => null],
    ['nom' => 'Vilbrequain WDFR TVS', 'reference' => 'VVD0101', 'prix_achat' => 8000, 'prix_vente' => 8800, 'image' => null],
    ['nom' => 'Vilbrequain Baja SM', 'reference' => 'VBQ0106', 'prix_achat' => 8500, 'prix_vente' => 9200, 'image' => null],
    ['nom' => 'Vilbrequain SM 150', 'reference' => 'VSM0102', 'prix_achat' => 8500, 'prix_vente' => 9300, 'image' => null],
    ['nom' => 'Cylindre TVS avatar', 'reference' => 'NML0536', 'prix_achat' => 8800, 'prix_vente' => 9500, 'image' => null],
    ['nom' => 'Villbrquain TVS SM', 'reference' => 'TGW0537', 'prix_achat' => 9500, 'prix_vente' => 10500, 'image' => null],
    ['nom' => 'Vilbrequain TVS YOG', 'reference' => 'VBT0107', 'prix_achat' => 9500, 'prix_vente' => 10500, 'image' => null],
    ['nom' => 'villbrequin Baja AVATAR', 'reference' => 'VCW0538', 'prix_achat' => 9900, 'prix_vente' => 10500, 'image' => null],
    ['nom' => 'Bidon d\'huile National noir 4 L', 'reference' => 'GMP0539', 'prix_achat' => 11333, 'prix_vente' => 12500, 'image' => null],
    ['nom' => 'Pneu CST 300-17', 'reference' => 'JAW0540', 'prix_achat' => 11500, 'prix_vente' => 12000, 'image' => null],
    ['nom' => 'Pneu 275-17 CST', 'reference' => 'PNC0140', 'prix_achat' => 12000, 'prix_vente' => 12600, 'image' => null],
    ['nom' => 'Pneu CST 300-18 NC', 'reference' => 'PNC0136', 'prix_achat' => 12000, 'prix_vente' => 13000, 'image' => null],
    ['nom' => 'culasse complete CG 150 JYC', 'reference' => 'EFU0541', 'prix_achat' => 12500, 'prix_vente' => 13500, 'image' => null],
    ['nom' => 'Marche arrière Complet PM', 'reference' => 'MAC0230', 'prix_achat' => 12500, 'prix_vente' => 13500, 'image' => null],
    ['nom' => 'Villbrequin CG 200', 'reference' => 'IWS0542', 'prix_achat' => 12500, 'prix_vente' => 13500, 'image' => null],
    ['nom' => 'Pneu CST 350-16 NC', 'reference' => 'PNC0137', 'prix_achat' => 13500, 'prix_vente' => 14000, 'image' => null],
    ['nom' => 'Reservoir P6 Simple', 'reference' => 'HAY0543', 'prix_achat' => 14000, 'prix_vente' => 15000, 'image' => null],
    ['nom' => 'Fourche avant senke', 'reference' => 'CSM0544', 'prix_achat' => 16500, 'prix_vente' => 17000, 'image' => null],
    ['nom' => 'Fourche avant Baja', 'reference' => 'FAB0308', 'prix_achat' => 16500, 'prix_vente' => 17500, 'image' => null],
    ['nom' => 'Fourche avant TVS', 'reference' => 'FAT0307', 'prix_achat' => 16500, 'prix_vente' => 17500, 'image' => null],
    ['nom' => 'Porte bagage Complet Senké', 'reference' => 'PBC0301', 'prix_achat' => 16500, 'prix_vente' => 18500, 'image' => null],
    ['nom' => 'Jante Baja', 'reference' => 'JNT0305', 'prix_achat' => 18000, 'prix_vente' => 19500, 'image' => null],
    ['nom' => 'Jante TVS', 'reference' => 'JTV0306', 'prix_achat' => 18000, 'prix_vente' => 19500, 'image' => null],
    ['nom' => 'Cartère Centrale Complet', 'reference' => 'CCC0245', 'prix_achat' => 24000, 'prix_vente' => 26000, 'image' => null],
];

        foreach ($produits as $produit) {
            Produit::firstOrCreate(
                ['reference' => $produit['reference']],
                $produit
            );
        }
    }
}
